version: 2.1
jobs:
  build:
    machine:
      image: android:2025.10.1
    steps:
      - checkout
      - run:
          name: Build APK
          command: ./gradlew assembleRelease
workflows:
  version: 2
  build_and_test:
    jobs:
      - build